-- GameRate V1 开发测试数据脚本
-- 仅用于本地开发或演示环境，正式环境不要执行。

USE `gamerate`;

INSERT INTO `user` (`username`, `password_hash`, `nickname`, `avatar_url`, `email`, `bio`, `status`, `is_deleted`)
VALUES
  ('test_user', '$2a$10$M3QR1QdjSCuiB8Z9Odow..6YHu3KF6gUL.4IbN4OVp1VvU0kVx2bK', '测试玩家', NULL, 'test_user@example.com', '用于本地开发测试的普通用户', 1, 0)
ON DUPLICATE KEY UPDATE
  `nickname` = VALUES(`nickname`),
  `bio` = VALUES(`bio`),
  `status` = VALUES(`status`),
  `is_deleted` = VALUES(`is_deleted`);

INSERT INTO `game` (
  `name`,
  `original_name`,
  `description`,
  `developer`,
  `publisher`,
  `release_date`,
  `category_id`,
  `platform_id`,
  `source_type`,
  `source_id`,
  `source_url`,
  `steam_app_id`,
  `cover_url`,
  `background_url`,
  `rawg_rating`,
  `metacritic_score`,
  `average_score`,
  `rating_count`,
  `view_count`,
  `comment_count`,
  `favorite_count`,
  `hot_score`,
  `status`,
  `is_deleted`,
  `create_time`,
  `update_time`
)
VALUES
  (
    'Elden Ring',
    'Elden Ring',
    'Open-world action role-playing game test data.',
    'FromSoftware',
    'Bandai Namco Entertainment',
    '2022-02-25',
    (SELECT `id` FROM `category` WHERE `code` = 'rpg' LIMIT 1),
    (SELECT `id` FROM `platform` WHERE `code` = 'steam' LIMIT 1),
    'MANUAL',
    'test-elden-ring',
    NULL,
    NULL,
    'https://placehold.co/600x800?text=Elden+Ring',
    'https://placehold.co/1600x900?text=Elden+Ring',
    NULL,
    NULL,
    0,
    0,
    0,
    0,
    0,
    0.00,
    1,
    0,
    NOW(),
    NOW()
  ),
  (
    'Black Myth: Wukong',
    'Black Myth: Wukong',
    'Action role-playing game test data.',
    'Game Science',
    'Game Science',
    '2024-08-20',
    (SELECT `id` FROM `category` WHERE `code` = 'action' LIMIT 1),
    (SELECT `id` FROM `platform` WHERE `code` = 'steam' LIMIT 1),
    'MANUAL',
    'manual-black-myth-wukong',
    NULL,
    NULL,
    'https://placehold.co/600x800?text=Black+Myth+Wukong',
    'https://placehold.co/1600x900?text=Black+Myth+Wukong',
    NULL,
    NULL,
    0,
    0,
    0,
    0,
    0,
    0.00,
    1,
    0,
    NOW(),
    NOW()
  ),
  (
    'Cyberpunk 2077',
    'Cyberpunk 2077',
    'Open-world role-playing game test data.',
    'CD PROJEKT RED',
    'CD PROJEKT RED',
    '2020-12-10',
    (SELECT `id` FROM `category` WHERE `code` = 'rpg' LIMIT 1),
    (SELECT `id` FROM `platform` WHERE `code` = 'steam' LIMIT 1),
    'MANUAL',
    'manual-cyberpunk-2077',
    NULL,
    NULL,
    'https://placehold.co/600x800?text=Cyberpunk+2077',
    'https://placehold.co/1600x900?text=Cyberpunk+2077',
    NULL,
    NULL,
    0,
    0,
    0,
    0,
    0,
    0.00,
    1,
    0,
    NOW(),
    NOW()
  ),
  (
    'The Witcher 3',
    'The Witcher 3: Wild Hunt',
    'Fantasy role-playing game test data.',
    'CD PROJEKT RED',
    'CD PROJEKT RED',
    '2015-05-19',
    (SELECT `id` FROM `category` WHERE `code` = 'rpg' LIMIT 1),
    (SELECT `id` FROM `platform` WHERE `code` = 'steam' LIMIT 1),
    'MANUAL',
    'manual-the-witcher-3',
    NULL,
    NULL,
    'https://placehold.co/600x800?text=The+Witcher+3',
    'https://placehold.co/1600x900?text=The+Witcher+3',
    NULL,
    NULL,
    0,
    0,
    0,
    0,
    0,
    0.00,
    1,
    0,
    NOW(),
    NOW()
  ),
  (
    'Hades',
    'Hades',
    'Roguelike action game test data.',
    'Supergiant Games',
    'Supergiant Games',
    '2020-09-17',
    (SELECT `id` FROM `category` WHERE `code` = 'indie' LIMIT 1),
    (SELECT `id` FROM `platform` WHERE `code` = 'steam' LIMIT 1),
    'MANUAL',
    'manual-hades',
    NULL,
    NULL,
    'https://placehold.co/600x800?text=Hades',
    'https://placehold.co/1600x900?text=Hades',
    NULL,
    NULL,
    0,
    0,
    0,
    0,
    0,
    0.00,
    1,
    0,
    NOW(),
    NOW()
  ),
  (
    'Hollow Knight',
    'Hollow Knight',
    'Metroidvania action-adventure game test data.',
    'Team Cherry',
    'Team Cherry',
    '2017-02-24',
    (SELECT `id` FROM `category` WHERE `code` = 'indie' LIMIT 1),
    (SELECT `id` FROM `platform` WHERE `code` = 'steam' LIMIT 1),
    'MANUAL',
    'manual-hollow-knight',
    NULL,
    NULL,
    'https://placehold.co/600x800?text=Hollow+Knight',
    'https://placehold.co/1600x900?text=Hollow+Knight',
    NULL,
    NULL,
    0,
    0,
    0,
    0,
    0,
    0.00,
    1,
    0,
    NOW(),
    NOW()
  ),
  (
    'Stardew Valley',
    'Stardew Valley',
    'Farming simulation game test data.',
    'ConcernedApe',
    'ConcernedApe',
    '2016-02-26',
    (SELECT `id` FROM `category` WHERE `code` = 'simulation' LIMIT 1),
    (SELECT `id` FROM `platform` WHERE `code` = 'steam' LIMIT 1),
    'MANUAL',
    'manual-stardew-valley',
    NULL,
    NULL,
    'https://placehold.co/600x800?text=Stardew+Valley',
    'https://placehold.co/1600x900?text=Stardew+Valley',
    NULL,
    NULL,
    0,
    0,
    0,
    0,
    0,
    0.00,
    1,
    0,
    NOW(),
    NOW()
  ),
  (
    'Red Dead Redemption 2',
    'Red Dead Redemption 2',
    'Open-world adventure game test data.',
    'Rockstar Games',
    'Rockstar Games',
    '2018-10-26',
    (SELECT `id` FROM `category` WHERE `code` = 'adventure' LIMIT 1),
    (SELECT `id` FROM `platform` WHERE `code` = 'pc' LIMIT 1),
    'MANUAL',
    'manual-red-dead-redemption-2',
    NULL,
    NULL,
    'https://placehold.co/600x800?text=Red+Dead+Redemption+2',
    'https://placehold.co/1600x900?text=Red+Dead+Redemption+2',
    NULL,
    NULL,
    0,
    0,
    0,
    0,
    0,
    0.00,
    1,
    0,
    NOW(),
    NOW()
  ),
  (
    'God of War',
    'God of War',
    'Action-adventure game test data.',
    'Santa Monica Studio',
    'Sony Interactive Entertainment',
    '2018-04-20',
    (SELECT `id` FROM `category` WHERE `code` = 'action' LIMIT 1),
    (SELECT `id` FROM `platform` WHERE `code` = 'playstation' LIMIT 1),
    'MANUAL',
    'manual-god-of-war',
    NULL,
    NULL,
    'https://placehold.co/600x800?text=God+of+War',
    'https://placehold.co/1600x900?text=God+of+War',
    NULL,
    NULL,
    0,
    0,
    0,
    0,
    0,
    0.00,
    1,
    0,
    NOW(),
    NOW()
  ),
  (
    'Baldur''s Gate 3',
    'Baldur''s Gate 3',
    'Party-based role-playing game test data.',
    'Larian Studios',
    'Larian Studios',
    '2023-08-03',
    (SELECT `id` FROM `category` WHERE `code` = 'rpg' LIMIT 1),
    (SELECT `id` FROM `platform` WHERE `code` = 'steam' LIMIT 1),
    'MANUAL',
    'manual-baldurs-gate-3',
    NULL,
    NULL,
    'https://placehold.co/600x800?text=Baldurs+Gate+3',
    'https://placehold.co/1600x900?text=Baldurs+Gate+3',
    NULL,
    NULL,
    0,
    0,
    0,
    0,
    0,
    0.00,
    1,
    0,
    NOW(),
    NOW()
  )
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `original_name` = VALUES(`original_name`),
  `description` = VALUES(`description`),
  `developer` = VALUES(`developer`),
  `publisher` = VALUES(`publisher`),
  `release_date` = VALUES(`release_date`),
  `category_id` = VALUES(`category_id`),
  `platform_id` = VALUES(`platform_id`),
  `source_type` = VALUES(`source_type`),
  `source_url` = VALUES(`source_url`),
  `steam_app_id` = VALUES(`steam_app_id`),
  `cover_url` = VALUES(`cover_url`),
  `background_url` = VALUES(`background_url`),
  `rawg_rating` = VALUES(`rawg_rating`),
  `metacritic_score` = VALUES(`metacritic_score`),
  `average_score` = VALUES(`average_score`),
  `rating_count` = VALUES(`rating_count`),
  `view_count` = VALUES(`view_count`),
  `comment_count` = VALUES(`comment_count`),
  `favorite_count` = VALUES(`favorite_count`),
  `hot_score` = VALUES(`hot_score`),
  `status` = VALUES(`status`),
  `is_deleted` = VALUES(`is_deleted`),
  `update_time` = NOW();

SET @test_user_id = (SELECT `id` FROM `user` WHERE `username` = 'test_user' LIMIT 1);
SET @test_game_id = (SELECT `id` FROM `game` WHERE `source_type` = 'MANUAL' AND `source_id` = 'test-elden-ring' LIMIT 1);

INSERT INTO `game_rating` (`user_id`, `game_id`, `score`, `content`, `status`, `is_deleted`)
VALUES
  (@test_user_id, @test_game_id, 9.5, '地图探索和战斗体验都很出色。', 1, 0)
ON DUPLICATE KEY UPDATE
  `score` = VALUES(`score`),
  `content` = VALUES(`content`),
  `status` = VALUES(`status`),
  `is_deleted` = VALUES(`is_deleted`);

INSERT INTO `game_comment` (`user_id`, `game_id`, `content`, `like_count`, `status`, `is_deleted`)
SELECT @test_user_id, @test_game_id, '这是一条用于开发联调的测试评论。', 0, 1, 0
WHERE NOT EXISTS (
  SELECT 1
  FROM `game_comment`
  WHERE `user_id` = @test_user_id
    AND `game_id` = @test_game_id
    AND `content` = '这是一条用于开发联调的测试评论。'
);

INSERT INTO `game_favorite` (`user_id`, `game_id`, `status`, `is_deleted`)
VALUES
  (@test_user_id, @test_game_id, 1, 0)
ON DUPLICATE KEY UPDATE
  `status` = VALUES(`status`),
  `is_deleted` = VALUES(`is_deleted`);
